# Generated by Django 3.0.7 on 2020-06-09 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('description', models.CharField(max_length=250, verbose_name='Description')),
                ('price', models.FloatField(verbose_name='Price')),
                ('time', models.IntegerField(verbose_name='Minutes')),
            ],
        ),
    ]
