# Generated by Django 3.0.7 on 2020-07-01 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='add_on',
            field=models.BooleanField(default=False, verbose_name='Add On'),
        ),
    ]
