# Generated by Django 3.0.7 on 2020-06-27 18:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('services', '0001_initial'),
        ('users', '0004_staff'),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lat', models.CharField(max_length=30, verbose_name='Latitude')),
                ('long', models.CharField(max_length=30, verbose_name='Longitude')),
                ('street_name', models.CharField(max_length=100, verbose_name='Street Number and Name')),
                ('details', models.CharField(blank=True, max_length=100, null=True, verbose_name='Details')),
                ('suburb', models.CharField(blank=True, max_length=100, null=True, verbose_name='Suburb')),
                ('state', models.CharField(blank=True, max_length=100, null=True, verbose_name='State')),
                ('postcode', models.CharField(max_length=50, verbose_name='Postcode')),
                ('country', models.CharField(max_length=50, verbose_name='Country')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='addresses', to='users.Customer')),
            ],
        ),
        migrations.CreateModel(
            name='booking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField(verbose_name='Start Time')),
                ('end_time', models.DateTimeField(verbose_name='End Time')),
                ('access_arrangments', models.CharField(choices=[('NO', 'No Private Access Required'), ('OW', 'Owner or Tenant will be at home'), ('KE', 'Pick up keys from office'), ('ST', 'Client staff member will attend'), ('SI', 'Keys available on site in lock box')], max_length=10, verbose_name='Access Arrangements')),
                ('key_no', models.CharField(blank=True, max_length=100, null=True, verbose_name='Key Number')),
                ('job_reference', models.CharField(blank=True, max_length=100, null=True, verbose_name='Client Job reference')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Notes')),
                ('private_notes', models.TextField(blank=True, null=True, verbose_name='Private Notes')),
                ('address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='booking.Address')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='users.Customer')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='services.Service')),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='users.Staff')),
            ],
        ),
    ]
