# Generated by Django 3.0.7 on 2020-07-07 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0003_auto_20200705_1401'),
        ('booking', '0003_auto_20200707_1826'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='service',
            field=models.ManyToManyField(blank=True, null=True, related_name='bookings', to='services.Service'),
        ),
    ]
