# Generated by Django 3.0.7 on 2020-07-07 14:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_staff'),
        ('booking', '0005_auto_20200707_1856'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='address',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings_customer', to='booking.Address'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings_address', to='users.Customer'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='staff',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bookings_services', to='users.Staff'),
        ),
    ]
