# Generated by Django 3.0.7 on 2020-12-23 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0009_address_full_addreess'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='project_folder',
            field=models.TextField(blank=True, null=True, verbose_name='Project Folder Name'),
        ),
    ]
